dependencies {
    runtimeOnly project(':data-access')
    implementation project(':domain')

    implementation platform('org.springframework.boot:spring-boot-dependencies:4.0.3')
    implementation 'org.springframework:spring-context'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
